# Generated by Django 5.0.7 on 2024-08-05 17:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('type', models.CharField(max_length=150, verbose_name='Type project')),
                ('background', models.ImageField(upload_to='uploads/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('code_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='View code URL')),
                ('run_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Run URL')),
                ('primary_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_skill', to='biography.skill', verbose_name='Primary skill')),
                ('skills', models.ManyToManyField(to='biography.skill', verbose_name='Skills')),
            ],
        ),
    ]
