# Generated by Django 5.0.7 on 2025-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
