# Generated by Django 5.0.7 on 2025-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='projects.contributor'),
        ),
    ]
