# Generated by Django 5.0.7 on 2024-08-05 17:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('colorType', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow')], max_length=30)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Job name')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('icon', models.ImageField(upload_to='jobs/')),
                ('time_start', models.DateField()),
                ('time_end', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('skills', models.CharField(default='HTML • CSS • JavaScript', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('icon', models.FileField(upload_to='icons/')),
                ('icon_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon (Font Awesome)')),
                ('background', models.CharField(blank=True, max_length=50, null=True, verbose_name='Background (hex)')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='biography.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biography.foldermodel')),
                ('jobs', models.ManyToManyField(to='biography.job', verbose_name='Jobs')),
                ('cats', models.ManyToManyField(to='biography.skillcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
