# Generated by Django 5.0.7 on 2024-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_remove_skill_icon_fa_skill_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Icon (svg code)'),
        ),
    ]
