# Generated by Django 5.0.7 on 2024-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_alter_skill_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
