# Generated by Django 5.0.7 on 2024-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_filemodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='cats',
            field=models.ManyToManyField(blank=True, null=True, to='biography.skillcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='biography.job', verbose_name='Jobs'),
        ),
    ]
