# Generated by Django 5.0.7 on 2024-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0005_alter_filemodel_cats_alter_filemodel_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='textAlign',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=15),
        ),
    ]
