# Generated by Django 5.0.7 on 2024-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0006_filemodel_textalign'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_filter',
            field=models.BooleanField(default=True),
        ),
    ]
