# Generated by Django 5.0.7 on 2024-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0007_skill_is_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='test', max_length=150, verbose_name='Company'),
            preserve_default=False,
        ),
    ]
