# Generated by Django 5.0.7 on 2024-08-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0008_remove_job_location_job_company'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.project', verbose_name='Projects'),
        ),
    ]
