# Generated by Django 5.0.7 on 2024-08-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0009_filemodel_projects'),
        ('projects', '0002_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='cats',
            field=models.ManyToManyField(blank=True, to='biography.skillcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='biography.job', verbose_name='Jobs'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.project', verbose_name='Projects'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Education title (University name)')),
                ('icon', models.FileField(upload_to='education/')),
                ('url', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time_start', models.DateField()),
                ('time_end', models.DateField(blank=True, null=True)),
                ('document_name', models.CharField(default='Serificate', max_length=25)),
                ('document', models.FileField(upload_to='education/files/')),
                ('skills', models.ManyToManyField(blank=True, to='biography.skill', verbose_name='Jobs')),
            ],
        ),
    ]
