# Generated by Django 5.0.7 on 2024-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0010_alter_filemodel_cats_alter_filemodel_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subname',
            field=models.CharField(default='', max_length=150, verbose_name='Your direction'),
            preserve_default=False,
        ),
    ]
