# Generated by Django 5.0.7 on 2024-08-30 10:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0011_education_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content'),
        ),
    ]
