# Generated by Django 5.0.7 on 2024-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0012_alter_education_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='educations',
            field=models.ManyToManyField(blank=True, to='biography.education'),
        ),
        migrations.AlterField(
            model_name='education',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='education/files/'),
        ),
    ]
