# Generated by Django 5.0.7 on 2024-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0013_filemodel_educations_alter_education_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='button_url',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_type',
            field=models.CharField(choices=[('default', 'Default'), ('image_page', 'Image page')], default='default', max_length=15),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
