# Generated by Django 5.0.7 on 2024-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0015_filemodel_is_contact_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_svg', models.TextField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='files/')),
                ('description', models.TextField()),
            ],
        ),
    ]
