# Generated by Django 5.0.7 on 2024-09-10 09:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0016_contact_primarybio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarybio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
