# Generated by Django 5.0.7 on 2024-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0017_alter_primarybio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarybio',
            name='photo',
            field=models.FileField(upload_to='files/'),
        ),
    ]
