# Generated by Django 5.0.7 on 2024-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0018_alter_primarybio_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
