# Generated by Django 5.0.7 on 2024-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0019_contact_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarybio',
            name='url_resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
